import { defineField, defineType } from "sanity";
import { gallerySizeWarning, imageFields, imageOptions, imageSizeWarning } from "./objects/imageWithAlt";

export const guestStory = defineType({
    name: "guestStory",
    title: "Guest Story",
    type: "document",
    groups: [
        { name: "content", title: "Content", default: true },
        { name: "media", title: "Media" },
        { name: "seo", title: "SEO" },
    ],
    fields: [
        defineField({
            name: "guestName",
            title: "Guest name",
            type: "string",
            group: "content",
            validation: (Rule) => Rule.required(),
        }),
        defineField({
            name: "guestLocation",
            title: "Guest home town",
            type: "string",
            group: "content",
            description: 'e.g. "Edinburgh".',
        }),
        defineField({
            name: "title",
            title: "Internal title",
            type: "string",
            group: "content",
            description: "Used only inside the Studio to tell stories apart — not shown on the site.",
            validation: (Rule) => Rule.required(),
        }),
        defineField({
            name: "slug",
            title: "Slug",
            type: "slug",
            group: "content",
            options: { source: "title", maxLength: 96 },
            validation: (Rule) => Rule.required(),
        }),
        defineField({
            name: "quote",
            title: "Pull quote",
            type: "text",
            rows: 2,
            group: "content",
            description: "The short, striking line shown in guest-story teasers.",
            validation: (Rule) => Rule.required(),
        }),
        defineField({
            name: "excerpt",
            title: "Excerpt",
            type: "text",
            rows: 2,
            group: "content",
            description: "A one-line summary shown under the headline.",
            validation: (Rule) => Rule.required(),
        }),
        defineField({
            name: "story",
            title: "Story",
            type: "text",
            rows: 10,
            group: "content",
            description: "The guest's account, in their words. Separate paragraphs with a blank line.",
            validation: (Rule) => Rule.required(),
        }),
        defineField({
            name: "travelled",
            title: "Travelled",
            type: "string",
            group: "content",
            description: 'When this guest travelled, e.g. "November 2025".',
        }),
        defineField({
            name: "journey",
            title: "Journey",
            type: "reference",
            to: [{ type: "itinerary" }],
            group: "content",
            description: "The itinerary this story is about.",
        }),
        defineField({
            name: "featured",
            title: "Featured",
            type: "boolean",
            group: "content",
            description: "The featured story is shown first on the Guest Stories page and on the home page.",
            initialValue: false,
        }),
        defineField({
            name: "publishedAt",
            title: "Published at",
            type: "datetime",
            group: "content",
            initialValue: () => new Date().toISOString(),
        }),

        defineField({
            name: "profileImage",
            title: "Guest portrait",
            type: "image",
            group: "media",
            description: "A small headshot-style photo. JPG, PNG or WebP — 2MB or smaller recommended.",
            options: imageOptions,
            fields: imageFields,
            validation: (Rule) => imageSizeWarning(2)(Rule).required(),
        }),
        defineField({
            name: "posterImage",
            title: "Film poster image",
            type: "image",
            group: "media",
            description:
                "The still shown before the film plays. Leave blank to use the first gallery image. JPG, PNG or WebP — 5MB or smaller recommended.",
            options: imageOptions,
            fields: imageFields,
            validation: imageSizeWarning(5),
        }),
        defineField({
            name: "gallery",
            title: "Gallery",
            type: "array",
            group: "media",
            description: "JPG, PNG or WebP — 3MB or smaller recommended per image.",
            of: [{ type: "image", options: imageOptions, fields: imageFields, validation: gallerySizeWarning(3) }],
        }),
        defineField({
            name: "videoUrl",
            title: "Video URL",
            type: "url",
            group: "media",
            description: "Optional YouTube or Vimeo link to the guest film.",
        }),

        defineField({
            name: "seo",
            title: "SEO",
            type: "seo",
            group: "seo",
        }),
    ],
    preview: {
        select: { title: "guestName", subtitle: "excerpt", media: "profileImage" },
    },
});
